"""
Report generation for Single Agent Workflow.

Generates comprehensive reports showing the cognitive workflow,
dissent management, confidence tracking, and performance metrics.
"""

from typing import List, Dict, Any
from datetime import datetime

from .utils import sanitize_for_markdown, format_timestamp_for_filename as format_timestamp
from .workflow import SingleAgentWorkflow

def generate_markdown_report(
    prompt: str,
    layer_outputs: List[Dict[str, Any]],
    final_output: str,
    metadata: Dict[str, Any],
    workflow: SingleAgentWorkflow
) -> str:
    """
    Generate a comprehensive markdown report for the single agent workflow.

    Args:
        prompt: Original user prompt
        layer_outputs: List of layer processing outputs
        final_output: Final agent response
        metadata: Workflow metadata
        workflow: SingleAgentWorkflow instance

    Returns:
        Formatted markdown report
    """
    timestamp = format_timestamp()
    num_layers = metadata.get("num_layers", 0)
    workflow_duration = metadata.get("workflow_duration", 0)
    total_tokens = metadata.get("total_tokens", 0)
    agents_used = metadata.get("agents_used", {})

    # Truncate original prompt for header
    truncated_prompt = prompt[:150] + "..." if len(prompt) > 150 else prompt

    markdown_content = f"""# Single Agent Workflow Response Report
**Generated:** {timestamp}

## System Configuration
- **Workflow Type:** Single Agent with Specialized Cognitive Functions
- **Layers Processed:** {num_layers}
- **Self-Review Enabled:** {metadata.get('self_review_enabled', False)}
- **Total Duration:** {workflow_duration:.2f}s
- **Total Tokens:** ~{total_tokens}

## Cognitive Function Models
- **Response Agent:** {agents_used.get('response', 'N/A')}
- **Devils Advocate:** {agents_used.get('devils_advocate', 'N/A')}
- **Synthesis Agent:** {agents_used.get('synthesis', 'N/A')}
- **Final Agent:** {agents_used.get('final', 'N/A')}

## Original Prompt
```
{prompt}
```

## Layer-by-Layer Analysis

"""

    # Add layer details
    for layer in layer_outputs:
        layer_num = layer.get("layer_number", 0)
        markdown_content += f"""### Layer {layer_num}

#### Response Agent
{sanitize_for_markdown(layer.get("response", "No response available"))}

"""

        if "self_review" in layer and layer["self_review"]:
            markdown_content += f"""#### Self-Review Assessment
{sanitize_for_markdown(layer.get("self_review", ""))}

"""

        if "devils_advocate" in layer:
            markdown_content += f"""#### Devils Advocate Critique
{sanitize_for_markdown(layer.get("devils_advocate", ""))}

"""

        if "synthesis" in layer:
            markdown_content += f"""#### Synthesis & Integration
{sanitize_for_markdown(layer.get("synthesis", ""))}

"""

    # Add final output
    markdown_content += f"""## Final Authoritative Answer

{sanitize_for_markdown(final_output)}

---
*Report generated by Single Agent Workflow Engine*
"""

    return markdown_content

def generate_detailed_markdown_report(
    prompt: str,
    layer_outputs: List[Dict[str, Any]],
    final_output: str,
    metadata: Dict[str, Any],
    workflow: SingleAgentWorkflow,
    tracer=None
) -> str:
    """
    Generate a detailed markdown report with full prompts and performance metrics.

    Args:
        prompt: Original user prompt
        layer_outputs: List of layer processing outputs
        final_output: Final agent response
        metadata: Workflow metadata
        workflow: SingleAgentWorkflow instance
        tracer: Optional tracer for additional metrics

    Returns:
        Detailed formatted markdown report
    """
    timestamp = format_timestamp()
    num_layers = metadata.get("num_layers", 0)
    workflow_duration = metadata.get("workflow_duration", 0)
    total_tokens = metadata.get("total_tokens", 0)
    agents_used = metadata.get("agents_used", {})

    markdown_content = f"""# Single Agent Workflow - Detailed Analysis Report
**Generated:** {timestamp}

## Executive Summary
- **Workflow Duration:** {workflow_duration:.2f} seconds
- **Layers Processed:** {num_layers}
- **Total Tokens:** ~{total_tokens}
- **Cognitive Functions:** 4 specialized models
- **Quality Assurance:** Self-review + Devils Advocate + Synthesis

## Cognitive Architecture

### Specialized Model Roles
| Cognitive Function | Model | Purpose |
|-------------------|-------|---------|
| Response Agent | {agents_used.get('response', 'N/A')} | Initial analysis and reasoning |
| Devils Advocate | {agents_used.get('devils_advocate', 'N/A')} | Critical challenge and stress-testing |
| Synthesis Agent | {agents_used.get('synthesis', 'N/A')} | Integration and dissent management |
| Final Agent | {agents_used.get('final', 'N/A')} | Authoritative decision making |

## Original User Prompt
```
{prompt}
```

## Detailed Layer Analysis

"""

    # Add detailed layer information
    for layer in layer_outputs:
        layer_num = layer.get("layer_number", 0)
        markdown_content += f"""### Layer {layer_num} Processing

#### 1. Response Agent Phase
**Model:** {agents_used.get('response', 'N/A')}
**Task:** Deep analysis and comprehensive reasoning

**Response:**
{sanitize_for_markdown(layer.get("response", "No response available"))}

"""

        if "response_prompt" in layer:
            markdown_content += f"""**Prompt Used:**
```
{sanitize_for_markdown(layer.get("response_prompt", ""))}
```

"""

        if "self_review" in layer and layer["self_review"]:
            markdown_content += f"""#### 2. Self-Review Phase
**Model:** {agents_used.get('response', 'N/A')} (same model, review prompt)
**Task:** Critical self-assessment of initial response

**Self-Review Assessment:**
{sanitize_for_markdown(layer.get("self_review", ""))}

**Review Prompt:**
```
{sanitize_for_markdown(layer.get("self_review_prompt", ""))}
```

"""

        if "devils_advocate" in layer:
            markdown_content += f"""#### 3. Devils Advocate Phase
**Model:** {agents_used.get('devils_advocate', 'N/A')}
**Task:** Aggressive critical challenge and contrarian viewpoints

**Devils Advocate Critique:**
{sanitize_for_markdown(layer.get("devils_advocate", ""))}

**Challenge Prompt:**
```
{sanitize_for_markdown(layer.get("devils_advocate_prompt", ""))}
```

"""

        if "synthesis" in layer:
            markdown_content += f"""#### 4. Synthesis Phase
**Model:** {agents_used.get('synthesis', 'N/A')}
**Task:** Integration with dissent management and unified narrative

**Synthesis & Integration:**
{sanitize_for_markdown(layer.get("synthesis", ""))}

**Synthesis Prompt:**
```
{sanitize_for_markdown(layer.get("synthesis_prompt", ""))}
```

"""

    # Add final agent section
    markdown_content += f"""## Final Agent Synthesis

### Final Authoritative Answer
**Model:** {agents_used.get('final', 'N/A')}
**Task:** Deliver authoritative final response with dissent surfacing

**Final Answer:**
{sanitize_for_markdown(final_output)}

### Final Agent Prompt
```
{metadata.get("final_prompt", "Prompt not available")}
```

## Performance Metrics

### Workflow Statistics
- **Total Processing Time:** {workflow_duration:.2f} seconds
- **Average Layer Time:** {workflow_duration/num_layers:.2f} seconds (for {num_layers} layers)
- **Total Token Usage:** ~{total_tokens} tokens
- **Tokens per Layer:** ~{total_tokens//num_layers if num_layers > 0 else 0} tokens

### Cognitive Function Utilization
- **Response Agent:** Used for initial analysis and self-review
- **Devils Advocate:** Applied stress-testing and critical challenge
- **Synthesis Agent:** Managed dissent and created unified narratives
- **Final Agent:** Provided authoritative conclusion

## Quality Assurance Features

### Dissent Management
- **Devils Advocate Integration:** Critical viewpoints preserved throughout
- **Synthesis Dissent Sections:** Explicitly marked dissenting points
- **Final Answer Balance:** Authoritative while acknowledging uncertainty

### Confidence Tracking
- **Assumption Identification:** [ASSUMPTION] tags throughout responses
- **Confidence Levels:** [HIGH/MEDIUM/LOW CONFIDENCE] assessments
- **Self-Review Mechanism:** Built-in quality validation

### Layered Refinement
- **Iterative Improvement:** Each layer builds on previous insights
- **Context Accumulation:** Growing knowledge base across layers
- **Convergence Validation:** Multiple perspectives integrated

## Conclusion

This Single Agent Workflow demonstrates the effectiveness of specialized cognitive functions working together to produce high-quality, well-reasoned responses. The combination of deep analysis, critical challenge, synthesis, and authoritative decision-making ensures comprehensive problem-solving with built-in quality assurance.

---
*Detailed report generated by Single Agent Workflow Engine v1.0.0*
"""

    return markdown_content

def generate_workflow_summary(
    metadata: Dict[str, Any],
    tracer=None
) -> str:
    """
    Generate a concise workflow summary for logging or quick reference.

    Args:
        metadata: Workflow metadata
        tracer: Optional tracer for additional stats

    Returns:
        Formatted summary string
    """
    duration = metadata.get("workflow_duration", 0)
    tokens = metadata.get("total_tokens", 0)
    layers = metadata.get("num_layers", 0)

    summary = f"""Single Agent Workflow Summary:
- Duration: {duration:.2f}s
- Layers: {layers}
- Tokens: ~{tokens}
- Self-Review: {metadata.get('self_review_enabled', False)}
- Models: {len(metadata.get('agents_used', {}))} cognitive functions
"""

    if tracer:
        stats = tracer.get_summary_stats()
        summary += f"- API Calls: {stats.get('total_api_calls', 0)}\n"
        summary += f"- Dissent Points: {stats.get('dissent_points_count', 0)}\n"
        summary += f"- Errors: {stats.get('error_count', 0)}\n"

    return summary